//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmAE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsmAE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;; part of Intel® 64 and IA-32 Architectures Software Developer’s Manual
        ///;; 
        ///[5.1 GENERAL-PURPOSE INSTRUCTIONS]
        ///;;The general-purpose instructions preform basic data movement, arithmetic, logic, program flow, and string opera-
        ///;;tions that programmers commonly use to write application and system software to run on Intel 64 and IA-32 
        ///;;processors. They operate on data contained in memory, in the general-purpose registers (EAX, EBX, ECX, EDX, 
        ///;;EDI, ESI, EBP, and ESP) and in the EFLAGS register. They  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string instruction_hints {
            get {
                return ResourceManager.GetString("instruction_hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DIRECTIVE]
        ///.386
        ///.386P
        ///.387
        ///.486
        ///.486P
        ///.586
        ///.586P
        ///.686
        ///.686P
        ///ALIAS
        ///ALIGN
        ///.ALLOCSTACK
        ///.ALPHA
        ///ASSUME
        ///.BREAK
        ///BYTE
        ///CATSTR
        ///.CODE
        ///COMM
        ///COMMENT
        ///.CONST
        ///.CONTINUE
        ///.CREF
        ///.DATA
        ///.DATA?
        ///DB
        ///DD
        ///DF
        ///.DOSSEG
        ///DOSSEG
        ///DQ
        ///DT
        ///DUP
        ///DW
        ///DWORD
        ///ECHO
        ///.ELSE
        ///ELSE
        ///ELSEIF
        ///ELSEIF2
        ///END
        ///.ENDIF
        ///ENDM
        ///ENDP
        ///.ENDPROLOG
        ///ENDS
        ///.ENDW
        ///EQU
        ///.ERR
        ///.ERR2
        ///.ERRB
        ///.ERRDEF
        ///.ERRDIF
        ///.ERRE
        ///.ERRIDN
        ///.ERRNB
        ///.ERRNDEF
        ///.ERRNZ
        ///EVEN
        ///.EXIT
        ///EXITM
        ///EXTERN
        ///EXTERNDEF
        ///EXTRN
        ///.FARDATA
        ///.FARDATA?
        ///FOR
        ///FORC
        ///.FPO
        ///FWORD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keywords {
            get {
                return ResourceManager.GetString("keywords", resourceCulture);
            }
        }
    }
}
